os:
  - linux
  - osx

dist: xenial

env:
  - MPI_LIBRARY=openmpi-4.0.1
  - MPI_LIBRARY=openmpi-3.1.4
  - MPI_LIBRARY=mpich-3.3.1

cache:
  directories:
  - $HOME/mpich-3.3.1-build
  - $HOME/openmpi-4.0.1-build
  - $HOME/openmpi-3.1.4-build

services:
  - xvfb

language: cpp

compiler:
  - clang
  - gcc

addons:
  homebrew:
    update: true
    packages:
      - cmake
  apt:
    update: true
    packages:
      - cmake
      - python3
      - python3-numpy
      - python3-matplotlib
      - python3-tk
      - python3-scipy

install:
  - echo $SHELL
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      pip3 install --user matplotlib
      pip3 install --user scipy
    fi
  - |
    pushd $HOME
    if [ -f "$MPI_LIBRARY-build/bin/mpiexec" ]
    then
      echo "mpiexec found, nothing to build"
    else
      if [ "${MPI_LIBRARY:0:7}" == "openmpi" ]
      then
        DOWNLOAD_URL="https://download.open-mpi.org/release/open-mpi/v${MPI_LIBRARY:8:3}/$MPI_LIBRARY.tar.gz"
        CONF_OPTIONS=
      elif [ "${MPI_LIBRARY:0:5}" == "mpich" ]
      then
        DOWNLOAD_URL="http://www.mpich.org/static/downloads/${MPI_LIBRARY:6:5}/$MPI_LIBRARY.tar.gz"
        CONF_OPTIONS="--disable-fortran"
      else
        echo "Invalid MPI library: $MPI_LIBRARY"
        exit 1
      fi
      echo "Downloading $MPI_LIBRARY source."
      wget "$DOWNLOAD_URL"
      tar -xzf "$MPI_LIBRARY.tar.gz"
      rm "$MPI_LIBRARY.tar.gz"
      echo "Configuring and building $MPI_LIBRARY source."
      cd "$MPI_LIBRARY"
      ./configure --prefix="$HOME/$MPI_LIBRARY-build" "$CONF_OPTIONS"
      make -j6
      make install
      cd -
      rm -rf "$MPI_LIBRARY"
    fi
    export PATH="$HOME/${MPI_LIBRARY}-build/bin:$PATH"
    export LD_LIBRARY_PATH="$HOME/${MPI_LIBRARY}-build/bin:$LD_LIBRARY_PATH"
    popd

script:
  - mkdir build && cd build && cmake .. && make -j6 && ctest --verbose
  - cd scaling && ./run-scaling.sh 2 2
  - cd ../examples/biased-coin-flip && ./run-cpp-abc-rejection-serial-example.sh 2
  - ./run-cpp-abc-rejection-mpi-example.sh 2
  - ./run-cpp-abc-smc-serial-example.sh 2
  - ./run-cpp-abc-smc-mpi-example.sh 2
  - ./run-python-abc-rejection-serial-example.sh 2
  - ./run-python-abc-rejection-mpi-example.sh 2
  - ./run-python-abc-smc-serial-example.sh 2
  - ./run-python-abc-smc-mpi-example.sh 2
  - cd ../sis-model && ./run-cpp-abc-rejection-serial-example.sh 2
  - ./run-cpp-abc-rejection-mpi-example.sh 2
  - sed 's;75.*35;75,70,65;' ./run-cpp-abc-smc-serial-example.sh > temp && mv temp ./run-cpp-abc-smc-serial-example.sh && chmod u+x ./run-cpp-abc-smc-serial-example.sh && ./run-cpp-abc-smc-serial-example.sh  2
  - sed 's;75.*35;75,70,65;' ./run-cpp-abc-smc-mpi-example.sh > temp && mv temp ./run-cpp-abc-smc-mpi-example.sh && chmod u+x ./run-cpp-abc-smc-mpi-example.sh && ./run-cpp-abc-smc-mpi-example.sh  2
  - ./run-python-abc-rejection-serial-example.sh 2
  - ./run-python-abc-rejection-mpi-example.sh 2
  - sed 's;75.*35;75,70,65;' ./run-python-abc-smc-serial-example.sh > temp && mv temp ./run-python-abc-smc-serial-example.sh && chmod u+x ./run-python-abc-smc-serial-example.sh && ./run-python-abc-smc-serial-example.sh  2
  - sed 's;75.*35;75,70,65;' ./run-python-abc-smc-mpi-example.sh > temp && mv temp ./run-python-abc-smc-mpi-example.sh && chmod u+x ./run-python-abc-smc-mpi-example.sh && ./run-python-abc-smc-mpi-example.sh  2
  - ./make-sis-trace.sh
