os:
  - linux
  - osx

dist: xenial

env:
  - MPI_LIBRARY=openmpi
  - MPI_LIBRARY=mpich

services:
  - xvfb

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - mpich
      - libmpich-dev
      - python3
      - python3-numpy
      - python3-matplotlib
      - python3-tk

        #  homebrew:
        #    packages:
        #      - openmpi
        #        #- mpich

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      pip3 install --user matplotlib

      if [ "$MPI_LIBRARY" = "openmpi" ]
      then
        echo 'brew "openmpi"' > Brewfile
      elif [ "$MPI_LIBRARY" = "mpich" ]
      then
        echo 'brew "mpich"' > Brewfile
      fi

      rvm $brew_ruby do brew bundle --verbose
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]
    then
      if [ "$MPI_LIBRARY" = "openmpi" ]
      then
        sudo update-alternatives --set mpi /usr/lib/openmpi/include
        sudo update-alternatives --set mpirun /usr/bin/mpirun.openmpi
      elif [ "$MPI_LIBRARY" = "mpich" ]
      then
        sudo update-alternatives --set mpi /usr/include/mpich
        sudo update-alternatives --set mpirun /usr/bin/mpirun.mpich
      fi
    fi

script:
  - mkdir build && cd build && cmake .. && make -j6 && ctest --verbose
  - cd scaling && ./run-scaling.sh
  - cd ../examples/biased-coin-flip && ./run-cpp-abc-rejection-serial-example.sh
  - ./run-cpp-abc-smc-serial-example.sh
  - ./run-python-abc-rejection-serial-example.sh
  - ./run-python-abc-smc-serial-example.sh
