os:
  - linux
  - osx

dist: xenial

services:
  - xvfb

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - python3
      - python3-numpy
      - python3-matplotlib
      - python3-tk

  homebrew:
    packages:
      - openmpi

install: [ "$TRAVIS_OS_NAME" == "osx" ] && pip3 install --user matplotlib

script:
  - mkdir build && cd build && cmake .. && make -j6 && ctest
  - cd scaling && ./run-scaling.sh
  - cd ../examples/biased-coin-flip && ./run-cpp-abc-rejection-serial-example.sh
  - ./run-cpp-abc-smc-serial-example.sh
  - ./run-python-abc-rejection-serial-example.sh
  - ./run-python-abc-smc-serial-example.sh
