os:
  - linux
  - osx

dist: xenial

env:
  - MPI_LIBRARY=openmpi-4.0.1
  - MPI_LIBRARY=openmpi-3.1.4
  - MPI_LIBRARY=mpich-3.3.1

cache:
  directories:
  - $HOME/mpich-3.3.1-build
  - $HOME/openmpi-4.0.1-build
  - $HOME/openmpi-3.1.4-build

services:
  - xvfb

language: cpp

compiler:
  - clang
  - gcc

addons:
  homebrew:
    update: true
    packages:
      - cmake
  apt:
    update: true
    packages:
      - cmake
      - python3
      - python3-numpy
      - python3-matplotlib
      - python3-tk
      - python3-scipy

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      pip3 install --user matplotlib
      pip3 install --user scipy
    fi
  - |
    pushd $HOME
    if [ "${MPI_LIBRARY:0:7}" == "openmpi" ]
    then
      if [ -f "${MPI_LIBRARY}-build/bin/mpiexec" ]
      then
        echo "mpiexec found, nothing to build"
      else
        echo "Downloading openmpi source."
        wget "https://download.open-mpi.org/release/open-mpi/v${MPI_LIBRARY:8:3}/${MPI_LIBRARY}.tar.gz"
        tar -xzf ${MPI_LIBRARY}.tar.gz
        rm ${MPI_LIBRARY}.tar.gz
        echo "Configuring and building openmpi source."
        cd ${MPI_LIBRARY}
        ./configure --prefix="$HOME/${MPI_LIBRARY}-build"
        make -j6
        make install
        cd -
        rm -rf ${MPI_LIBRARY}
      fi
    elif [ "$MPI_LIBRARY" == "mpich-3.3.1" ]
    then
      if [ -f "${MPI_LIBRARY}-build/bin/mpiexec" ]
      then
        echo "mpiexec found, nothing to build"
      else
        echo "Downloading mpich source."
        wget http://www.mpich.org/static/downloads/3.3.1/mpich-3.3.1.tar.gz
        tar -xzf ${MPI_LIBRARY}.tar.gz
        rm ${MPI_LIBRARY}.tar.gz
        echo "Configuring and building mpich source."
        cd ${MPI_LIBRARY}
        ./configure --prefix="$HOME/${MPI_LIBRARY}-build" --disable-fortran
        make -j6
        make install
        cd -
        rm -rf ${MPI_LIBRARY}
      fi
    fi
    export PATH="$HOME/${MPI_LIBRARY}-build/bin:$PATH"
    export LD_LIBRARY_PATH="$HOME/${MPI_LIBRARY}-build/bin:$LD_LIBRARY_PATH"
    popd

script:
  - mkdir build && cd build && cmake .. && make -j6 && ctest --verbose
  - cd scaling && ./run-scaling.sh
  - cd ../examples/biased-coin-flip && ./run-cpp-abc-rejection-serial-example.sh
  - ./run-cpp-abc-rejection-mpi-example.sh
  - ./run-cpp-abc-smc-serial-example.sh
  - ./run-cpp-abc-smc-mpi-example.sh
  - ./run-python-abc-rejection-serial-example.sh
  - ./run-python-abc-rejection-mpi-example.sh
  - ./run-python-abc-smc-serial-example.sh
  - ./run-python-abc-smc-mpi-example.sh
  - cd ../sis-model && ./run-abc-rejection-serial-example.sh
  - ./run-abc-rejection-mpi-example.sh
  - ./run-abc-smc-serial-example.sh
  - ./run-abc-smc-mpi-example.sh
