dist: xenial

services:
  - xvfb

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - python3
      - python3-numpy
      - python3-matplotlib
      - python3-tk

script:
  - mkdir build && cd build && cmake .. && make -j6 && ctest
  - cd scaling && ./run-scaling.sh
  - cd ../examples/biased-coin-flip && ./run-cpp-example.sh 
  - ./run-python-example.sh
